### ISSUE TITLE
Help - How to change endpoints from localhost to IP?

### ISSUE THREAD

**Issue by DamiToma** [useaurora/aurora#79]
First, great app!<br>
Just installed Aurora with Docker but I'm not able to set it up. The problem is all calls are refused and I guess it's because they're sent to localhost rather than my server's IP. This is my `.yml` configuration file:

```
version: "3.7"
services:
  ui:
    image: ghcr.io/useaurora/aurora/aurora
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://1.1.1.1:5000
    depends_on:
      - postgres

  api:
    image: ghcr.io/useaurora/api/api
    ports:
      - "5000:5000"
    environment:
      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: aurora
      DB_USERNAME: aurora
      DB_PASSWORD: aurora
      DB_SSL: "false"

      JWT_SECRET: djd83ng94hf03hf93j
      AUTH_MODE: jwt
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: aurora
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: aurora
    volumes:
      - aurora_postgres:/var/lib/postgresql/data

volumes:
  aurora_postgres:
```

Basically copied from the docs and changed from `localhost` to my own IP in the `NEXT_PUBLIC_API_URL` parameter.  Pretty sure I'm doing something wrong! How do I fix this? Thanks!
